#pragma once
// ============================================================================
// PERIODIC packing — layout primitives (header-only; NOT wired into PackingKind
// or any dispatcher yet, so this file is inert until something includes it).
//
// ---------------------------------------------------------------------------
// WHY
// ---------------------------------------------------------------------------
// Measured, tests/test_ptmult_isolation.cu (job 49896185, level 19, 8 limbs):
// one ct x pt multiply costs 1620.1 us, of which the arithmetic is 8.3 us
// (0.51 %) and the plaintext host->device round trip is 873.9 us (53.9 %; 68 %
// at the production 11-limb point). A ViT-B forward ships 9216 weight
// plaintexts per block x 12 blocks = 110 592, ~463 GB across the bus.
//
// Each of those plaintexts carries only d_out distinct numbers. In the
// incumbent diagonal/filling layout the weight diagonal is BLOCK-CONSTANT
//
//     diag[j * t_out + tok] = W[row][j];        // diagonal_linear_utils.cu:65-101
//     i.e.  m[s] = w[ floor(s / t_out) ]
//
// 32x redundant, but block-constant slot vectors have no structure the encoder
// can exploit: the encoded (evaluation-domain, RNS) limbs are dense, so all N
// residues per limb cross the bus.
//
// The transpose is PERIODIC:
//
//     diag[tok * d + i] = w[i];                 //  m[s] = w[s mod d]
//
// A d-periodic slot vector is exactly the sparse (d-slot) encoding of w: its
// polynomial lies in the subring generated by X^(N/2d). That is the same
// subring fact SPARSE_BTS_SLOTS already exploits on the ciphertext side, used
// here on the plaintext side. A polynomial in that subring takes at most 2d
// distinct values across its N evaluation points, so the limb can be stored and
// shipped as (<=2d unique residues + an index map) rather than N residues.
//
//   *** THIS IS THE PREMISE, NOT A RESULT. ***
// tests/test_periodic_layout.cu measures the distinct-residue count of the
// limbs FIDESlib actually uploads (GetAllElements(), post bit-reverse). Nothing
// should be built on this header until that gate is green, and even then the
// saving is only realised once the transfer path stores the compressed form —
// RawPlainText::sub_0 is vector<vector<uint64_t>>[numRes][N] today, i.e. dense
// regardless of the `slots` field.
//
// ---------------------------------------------------------------------------
// WHAT IT COSTS
// ---------------------------------------------------------------------------
// Token-major means a global rotation no longer acts per token. The BSGS matvec
// needs a rotation that is cyclic WITHIN each d-block; a global rotation by k
// bleeds across the block boundary. Decompose it (see block_rot_terms):
//
//     blockrot_k(x) = lo_k * rot_k(x) + hi_k * rot_{k-d}(x)
//     lo_k[s] = [ (s mod d) <  d-k ]
//     hi_k[s] = [ (s mod d) >= d-k ]
//
// Both masks are themselves d-periodic, so fold them into the diagonal and the
// mask multiplies vanish (see folded_diag_periods):
//
//     diag_k * blockrot_k(x)
//         = (lo_k*diag_k) * rot_k(x) + (hi_k*diag_k) * rot_{k-d}(x)
//
// Cost: 2 rotations and 2 plaintexts per diagonal instead of 1 and 1 (k=0 stays
// single). Both plaintexts remain d-periodic, so weight bytes go as 2/(2d/N) —
// a 16x reduction at d=1024, N=65536 — while rotations double. That trade is
// the whole thesis: rotations were measured at ~12.6 % of the ViT wall
// (vit-per-op-timed-verdict) and hoisting amortises the pair, against a
// plaintext term measured at 54-68 %.
//
// OPEN, NOT SOLVED HERE: the BSGS giant-step rotation of the accumulator needs
// the same decomposition, and there its masks cannot be folded into a weight
// (a rotation followed by an add, not a multiply). Cost it before committing to
// a full linear.
// ============================================================================

#include <cstddef>
#include <stdexcept>
#include <string>
#include <vector>

namespace periodic {

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

struct Params {
    int d = 0;       // feature dimension (period). Power of 2, divides slots.
    int slots = 0;   // CKKS slot count (N/2)
    int T = 0;       // tokens per ciphertext = slots / d
};

inline Params make_params(int d, int slots) {
    if (d <= 0 || slots <= 0)
        throw std::runtime_error("periodic::make_params: d and slots must be positive");
    if (slots % d != 0)
        throw std::runtime_error("periodic::make_params: slots must be a multiple of d (got d=" +
                                 std::to_string(d) + ", slots=" + std::to_string(slots) + ")");
    if ((d & (d - 1)) != 0)
        throw std::runtime_error("periodic::make_params: d must be a power of 2 for the subring "
                                 "argument to hold (got d=" + std::to_string(d) + ")");
    Params p;
    p.d = d;
    p.slots = slots;
    p.T = slots / d;
    return p;
}

// Token-major: token `tok` owns the contiguous block [tok*d, (tok+1)*d).
inline int slot_of(int tok, int i, int d) { return tok * d + i; }

// The incumbent feature-major map, for side-by-side comparison in tests.
inline int slot_of_feature_major(int tok, int i, int t) { return i * t + tok; }

// ---------------------------------------------------------------------------
// Period <-> slot vector
// ---------------------------------------------------------------------------

// Replicate a length-d period across `slots`. The result IS the sparse d-slot
// encoding of `period`; expanding it here is only for the dense encode path and
// for host-side reference checks.
inline std::vector<double> expand(const std::vector<double>& period, int slots) {
    const int d = static_cast<int>(period.size());
    if (d == 0 || slots % d != 0)
        throw std::runtime_error("periodic::expand: slots must be a multiple of period length");
    std::vector<double> v(static_cast<size_t>(slots));
    for (int s = 0; s < slots; ++s) v[s] = period[s % d];
    return v;
}

// True iff v[s] depends only on (s mod d) — the compressibility precondition.
inline bool is_periodic(const std::vector<double>& v, int d, double tol = 0.0) {
    const int n = static_cast<int>(v.size());
    if (d <= 0 || n % d != 0) return false;
    for (int s = d; s < n; ++s) {
        const double a = v[s], b = v[s % d];
        if (!(a == b || (a - b <= tol && b - a <= tol))) return false;
    }
    return true;
}

// True iff v[s] depends only on floor(s / blk) — what the incumbent layout
// produces. Present so a test can assert the two are genuinely different
// structures rather than two names for the same thing.
inline bool is_block_constant(const std::vector<double>& v, int blk) {
    const int n = static_cast<int>(v.size());
    if (blk <= 0 || n % blk != 0) return false;
    for (int s = 0; s < n; ++s)
        if (v[s] != v[(s / blk) * blk]) return false;
    return true;
}

// ---------------------------------------------------------------------------
// Weights
// ---------------------------------------------------------------------------
// W is row-major d x d: W[j*d + i] = W[j][i], y[j] = sum_i W[j][i] * x[i].
// Halevi-Shoup: y = sum_k diag_k * blockrot_k(x), diag_k[i] = W[i][(i+k) % d].
// diag_k depends on i only, so as a slot vector it is d-periodic by construction
// — that is the entire point of this layout.

inline std::vector<double> weight_diag_period(const std::vector<double>& W, int d, int k) {
    if (static_cast<int>(W.size()) != d * d)
        throw std::runtime_error("periodic::weight_diag_period: W must be d*d row-major");
    if (k < 0 || k >= d)
        throw std::runtime_error("periodic::weight_diag_period: k out of range");
    std::vector<double> diag(static_cast<size_t>(d));
    for (int i = 0; i < d; ++i) diag[i] = W[static_cast<size_t>(i) * d + ((i + k) % d)];
    return diag;
}

// ---------------------------------------------------------------------------
// Block-cyclic rotation
// ---------------------------------------------------------------------------

struct BlockRotTerm {
    int rot = 0;                        // global rotation step (may be negative)
    std::vector<double> mask_period;    // d-periodic selector
    bool empty = false;                 // true when this term contributes nothing
};

// blockrot_k(x)[tok*d + i] = x[tok*d + ((i+k) % d)]
//   = lo_k * rot_k(x) + hi_k * rot_{k-d}(x)
inline std::vector<BlockRotTerm> block_rot_terms(int k, int d) {
    if (d <= 0) throw std::runtime_error("periodic::block_rot_terms: d must be positive");
    k = ((k % d) + d) % d;

    BlockRotTerm lo;
    lo.rot = k;
    lo.mask_period.assign(static_cast<size_t>(d), 0.0);
    for (int i = 0; i < d; ++i) if (i < d - k) lo.mask_period[i] = 1.0;

    BlockRotTerm hi;
    hi.rot = k - d;
    hi.mask_period.assign(static_cast<size_t>(d), 0.0);
    for (int i = 0; i < d; ++i) if (i >= d - k) hi.mask_period[i] = 1.0;
    hi.empty = (k == 0);   // k=0 is the identity: no wrap term, single plaintext

    return {lo, hi};
}

// The plaintexts actually multiplied: the diagonal with the block-rotation mask
// folded in, so the mask multiplies cost nothing. Each stays d-periodic (a
// product of two d-periodic vectors), hence each stays compressible.
inline std::vector<BlockRotTerm> folded_diag_periods(const std::vector<double>& diag_period,
                                                     int k, int d) {
    if (static_cast<int>(diag_period.size()) != d)
        throw std::runtime_error("periodic::folded_diag_periods: diag_period must have length d");
    std::vector<BlockRotTerm> terms = block_rot_terms(k, d);
    for (auto& t : terms)
        for (int i = 0; i < d; ++i) t.mask_period[i] *= diag_period[i];
    return terms;
}

// ---------------------------------------------------------------------------
// Host references (ground truth for the FHE gate)
// ---------------------------------------------------------------------------

// Global cyclic left rotation: out[s] = x[(s + r) mod n]. Matches OpenFHE
// EvalRotate's sign convention (positive = left).
inline std::vector<double> rot_reference(const std::vector<double>& x, int r) {
    const int n = static_cast<int>(x.size());
    std::vector<double> out(static_cast<size_t>(n));
    for (int s = 0; s < n; ++s) out[s] = x[(((s + r) % n) + n) % n];
    return out;
}

// Per-token cyclic rotation — what the matvec needs and what a global rotation
// does not give.
inline std::vector<double> block_rot_reference(const std::vector<double>& x, int k, int d) {
    const int n = static_cast<int>(x.size());
    if (d <= 0 || n % d != 0)
        throw std::runtime_error("periodic::block_rot_reference: size must be a multiple of d");
    k = ((k % d) + d) % d;
    std::vector<double> out(static_cast<size_t>(n));
    for (int s = 0; s < n; ++s) {
        const int tok = s / d, i = s % d;
        out[s] = x[static_cast<size_t>(tok) * d + ((i + k) % d)];
    }
    return out;
}

// Per-token y = W x, laid out token-major.
inline std::vector<double> matvec_reference(const std::vector<double>& W,
                                            const std::vector<double>& x, int d) {
    const int n = static_cast<int>(x.size());
    if (n % d != 0) throw std::runtime_error("periodic::matvec_reference: size % d != 0");
    std::vector<double> y(static_cast<size_t>(n), 0.0);
    for (int tok = 0; tok < n / d; ++tok)
        for (int j = 0; j < d; ++j) {
            double acc = 0.0;
            for (int i = 0; i < d; ++i)
                acc += W[static_cast<size_t>(j) * d + i] * x[static_cast<size_t>(tok) * d + i];
            y[static_cast<size_t>(tok) * d + j] = acc;
        }
    return y;
}

// ---------------------------------------------------------------------------
// Accounting
// ---------------------------------------------------------------------------

// Upper bound on distinct residues per limb for a d-periodic slot vector: the
// polynomial lies in the subring generated by X^(N/2d), so its N evaluation
// points collapse onto at most 2d values. `slots` = N/2.
inline int distinct_residue_bound(int d, int slots) {
    const int n_coeff = 2 * slots;                 // N
    const int bound = 2 * d;
    return bound < n_coeff ? bound : n_coeff;
}

// Bytes per limb once only the unique residues are stored, vs dense today.
inline double compression_ratio(int d, int slots) {
    return static_cast<double>(2 * slots) / static_cast<double>(distinct_residue_bound(d, slots));
}

}  // namespace periodic
