# Keep the working directory unchanged and suppress hydra output dirs/logging.
# https://github.com/facebookresearch/hydra/issues/910
run:
  dir: .
sweep:
  dir: .
  subdir: .

output_subdir: null

defaults:
  - override job_logging: none
  - override hydra_logging: none
